FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY alerting /app/alerting
COPY log-processor/src/kvstore_client.py /app/alerting/
COPY config /app/config

WORKDIR /app/alerting

CMD ["python", "alert_manager.py"]
